### ISSUE TITLE
kubectl cp doesn't work properly

### ISSUE THREAD

**Issue by sebbalex** [teamdigitale/devops-tools#4]
Using `kubectl cp` to copy from/to container we are actually copying data inside and from container and not local host.
Maybe we should define a preset volume to do these kind operations, a folder inside `/tmp` ?

cc @LucaPrete

**Comment by LucaPrete** [comment]
Yes! Good point. I’ll take care of it

Il giorno gio 23 lug 2020 alle 13:04 Alessandro Sebastiani <
notifications@github.com> ha scritto:

**Comment by sebbalex** [comment]
Closed by 6e65c7f
thanks @LucaPrete
