### ISSUE TITLE
Exposed ports are not available

### ISSUE THREAD

**Issue by sebbalex** [teamdigitale/devops-tools#5]
Using `kubectl port-forward` will expose specified port from remote container to local host. As of now this is not working because they will exposed at local container level, which is started when invoking `kubectl` command itself, and not at localhost context. And I'm afraid this makes feature unusable.

cc @LucaPrete

**Comment by LucaPrete** [comment]
@sebbalex solved. FYI https://github.com/teamdigitale/devops-tools/commit/5aacb4cb0720f9a0fdfa8885a9347ef20295086a
